### ISSUE TITLE
An error occured while selecting the store state: idsToGetFromStore.map is not a function.

### ISSUE THREAD

**Issue by volodymyrd** [marmelab/react-admin#4090]
**What you were expecting:**

Expect to select items in ReferenceArrayInput component.
**What happened instead:**

When select any first item in a list get "Something went wrong".
**Steps to reproduce:**

add to the simple example to PostCreate.js file before close tag SimpleForm this code:
```
                <ReferenceArrayInput
                    reference="tags"
                    source="tags"
                    filter={{ published: true }}
                >
                    <AutocompleteArrayInput fullWidth />
                </ReferenceArrayInput>
```
then run app and on the Post page create a new Post then try to add a new tag.
**Related code:**

* Preferably, a CodeSandbox forked from https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

```
insert short code snippets here
```

**Other information:**

**Environment**

* React-admin version: 3.0.0
* Last version that did not exhibit the issue (if applicable): 2.9.8
* React version: 16.9.0
* Browser: Chrome
* Stack trace (in case of a JS error):
idsToGetFromStore.map is not a function.
    at useSelectorWithStoreAndSubscription (useSelector.js:47)
    at useSelector (useSelector.js:112)
    at useReferenceArrayInputController (useReferenceArrayInputController.ts:55)
    at ReferenceArrayInput (ReferenceArrayInput.js:115)
    at renderWithHooks (react-dom.development.js:15108)
    at updateFunctionComponent (react-dom.development.js:16925)
    at beginWork$1 (react-dom.development.js:18498)
    at HTMLUnknownElement.callCallback (react-dom.development.js:347)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:397)
    at invokeGuardedCallback (react-dom.development.js:454)

**Comment by volodymyrd** [comment]
I'm able to fix the issue change the condition [here](https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/controller/input/useReferenceArrayInputController.ts#L62) to:
if (newIdsToFetch.length > 0 && inputValue.current)

**Comment by wmwart** [comment]
In version 3.0.1 everything seemed to work, it stopped working with the transition to version 3.0.2

**Comment by volodymyrd** [comment]
Yes it works locally for 3.0.0 and 3.0.1 but when I create a build with yarn run build I get very similar error
<img width="567" alt="Screenshot 2019-12-02 at 10 26 16" src="https://user-images.githubusercontent.com/3913102/69947723-8b4be400-14ee-11ea-9659-2f1028aed78f.png">

**Comment by fzaninotto** [comment]
Reproduced and confirmed, thanks for the report.
