### ISSUE TITLE
List show nothing when http error after upgraded to v4

### ISSUE THREAD

**Issue by mytharcher** [marmelab/react-admin#8241]
**What you were expecting:**

`<List>` should at least show some normal components when error happens, such as filter, grid (with old data), pagination and others which not cause the error.

**What happened instead:**

After upgraded to v4, if HTTP error happens, all `<List>` show nothing like abnormal.

**Steps to reproduce:**

Something same as in #7415, just return a 500 error from any loading in list.

**Related code:**

https://github.com/marmelab/react-admin/commit/5cc275af36120e4153eafe6a884c5578a0f2ea3b

```
if (error) {
    return null;
}
```

This logic is so simple and rough to fix the old issue.

**Other information:**

**Environment**

* React-admin version: 4.4.0
* Last version that did not exhibit the issue (if applicable): 3.19.0
* React version: 17.0.2
* Browser: Chrome 105.0.5195.125
* Stack trace (in case of a JS error):

Console error:

```
react_devtools_backend.js:4026 Error
    at new HttpError (HttpError.ts:15:1)
    at fetch.ts:50:1
```

HTTP response:

```json
{"timestamp":1665035231396,"error":{"key":"error.unknown"}}
```

**Comment by slax57** [comment]
Hi, and thank you for submitting this issue.
I agree that this is something that could be improved, for example we could display the data we have, even though the last fetch ended up with an error.
I'll mark this as an enhancement request.
Feel free to open a PR if you would like to submit an improvement for this.

**Comment by IshFx** [comment]
Hi everyone,

For me, this is a bug and not an enhancement.

The filter inputs that caused the backend error are saved to the local storage as specified in the docs :
![image](https://user-images.githubusercontent.com/23222270/196924076-643c87d9-b4d5-46e0-8d71-9f7a07296d2d.png)

This causes the List page to show nothing because the filter inputs are always being sent at page loading.
The only solution i found right now is to ask users to clear their cache (and by extension their local storage).
The backend error is completely normal because it reflects an erroneous query.

The desired solution would be to display at least the filter bar, so the user can correct their filter inputs.

Thanks in advance.

**Comment by mytharcher** [comment]
@IshFx That is totally correct. And I think the erroneous filter should not be persisted.
