### ISSUE TITLE
Can't use withDataProvider

### ISSUE THREAD

**Issue by zhouhao27** [marmelab/react-admin#3865]
**What you were expecting:**

**What happened instead:**

Get the following error message when using `withDataProvider`:

> Warning: React does not recognize the `dataProvider` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `dataprovider` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

Actually there are two errors, the other one is for getList:

> index.js:1375 Error: Error processing request
    at getList (methods.js:219)
    at RestProvider.js:87

**Steps to reproduce:**

**Related code:**

* Preferably, a CodeSandbox you can fork this one: https://codesandbox.io/s/github/marmelab/react-admin/tree/master/examples/simple
* A link to a GitHub repo with the minimal codebase to reproduce the issue

The **tags** is a collection in my `Firebase`.

```
class PostCreate extends React.Component {
  state = {
    tags: []
  }

  componentDidMount() {
    const { dataProvider } = this.props
    dataProvider('GET_LIST', 'tags', {})
      .then(({ data: tags }) => {
        console.log(tags)
        this.setState({ tags })
      })
      .catch(error => console.error(error))

    // .catch(error => dispatch(showNotification(error.message, 'error')))    
  }

  render() {
    const { tags } = this.state
    return (
      <Create {...this.props}>
        <SimpleForm>
          <TextInput source="title" />
          <TextInput source="teaser" options={{ multiline: true }} />
          <RichTextInput source="body" />
          <AutocompleteArrayInput source="tags" choices={tags} />
          <DateTimeInput label="Publication date" source="published_at" defaultValue={new Date()} />
        </SimpleForm>
      </Create>  
    )
  }
}

PostCreate.propTypes = {
  dataProvider: PropTypes.func.isRequired
}

export default withDataProvider(PostCreate)
```

**Other information:**

**Environment**

* React-admin version: 3.0.0-beta.2
* Last version that did not exhibit the issue (if applicable):
* React version:
* Browser:
* Stack trace (in case of a JS error):

**Comment by djhi** [comment]
`dataProvider` is not a prop accepted by `Create`. You need to pass it all props except `dataProvider`

**Comment by fzaninotto** [comment]
you can still use `withDataProvider`, but you can't pass all props to the `Create` element in `render`.

**Comment by djhi** [comment]
```js
const { dataProvider, ...props } = this.props;

<Create {...props}>
```

**Comment by zhouhao27** [comment]
@djhi Thanks. I'm not so familiar with ES6. Anyway, it works now.

But the other error message is still there:

> index.js:1375 Error: Error processing request
    at getList (methods.js:219)
    at RestProvider.js:87

My code is:
```
    dataProvider.getList('tags', {
      sort: { field: 'id', order: 'DESC' }
    }).then((response) => {
      console.log(response)
      // this.setState({ tags })
    })
    .catch(error => console.error(error))
```

When I debug, it just stop at this line:

```
throw new Error('The onSuccess option must be a function');
```

But I just followed the [example](https://github.com/marmelab/react-admin/pull/2899). It is just a promise, right?

**Comment by fzaninotto** [comment]
I can't reproduce your error. the below code works with `withDataProvider` in 3.0.0:

```jsx
    useEffect(() => {
        dataProvider
            .getList('tags', {
                sort: { field: 'id', order: 'DESC' },
                pagination: { page: 1, perPage: 10 },
            })
            .then(({ data: tags }) => {
                console.log(tags);
            })
            .catch(error => console.error(error));
    }, []);
```

If there is a problem, I believe it's in your code rather than in react-admin. So unless you can post a CodeSandbox demonstrating you issue, I recommend you ask your "HowTo" questions on StackOverflow - this issue trackers is only for react-admin bugs.

**Comment by zhouhao27** [comment]
Thanks for your all. It works now. The key is:
```
sort: { field: 'id', order: 'DESC' },
pagination: { page: 1, perPage: 10 },
```

Have to use both, otherwise will get error.
